/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.museumapplication.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

import java.util.Date;

/**
 * Definition of ObjectType Artifact.
 *
 * @since 2020-09-01
 */
public class Artifact extends CloudDBZoneObject {
    @PrimaryKey
    @IsIndex(indexName = "artifactIndex")
    private Integer artifactID;

    private String artifactName;

    private Text artifactDescription;

    private Text artifactImage;

    public Artifact() {
        super();

    }
    public void setArtifactID(Integer artifactID) {
        this.artifactID = artifactID;
    }

    public Integer getArtifactID() {
        return artifactID;
    }

    public void setArtifactName(String artifactName) {
        this.artifactName = artifactName;
    }

    public String getArtifactName() {
        return artifactName;
    }

    public void setArtifactDescription(Text artifactDescription) {
        this.artifactDescription = artifactDescription;
    }

    public Text getArtifactDescription() {
        return artifactDescription;
    }

    public void setArtifactImage(Text artifactImage) {
        this.artifactImage = artifactImage;
    }

    public Text getArtifactImage() {
        return artifactImage;
    }

}
