/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.museumapplication.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

/**
 * Definition of ObjectType LinkedAccount.
 *
 * @since 2020-12-24
 */
public class LinkedAccount extends CloudDBZoneObject {

    @PrimaryKey
    private String linkedID;

    @NotNull
    @DefaultValue(stringValue = "NA")
    private String accountID;

    public LinkedAccount() {
        this.accountID = "NA";

    }
    public LinkedAccount(String linkedID, String accountID) {
        this.linkedID = linkedID;
        this.accountID = accountID;
    }
    public void setLinkedID(String linkedID) {
        this.linkedID = linkedID;
    }

    public String getLinkedID() {
        return linkedID;
    }

    public void setAccountID(String accountID) {
        this.accountID = accountID;
    }

    public String getAccountID() {
        return accountID;
    }

}
