/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.museumapplication.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

import java.util.Date;

/**
 * Definition of ObjectType LinkedAccount.
 *
 * @since 2020-08-12
 */
public class LinkedAccount extends CloudDBZoneObject {
    @PrimaryKey
    private String LinkedID;

    @NotNull
    @IsIndex(indexName = "index")
    @DefaultValue(stringValue = "NA")
    private String AccountID;

    public LinkedAccount() {
        super();
        this.AccountID = "NA";

    }
    public LinkedAccount(String LinkedID, String AccountID) {
        this.LinkedID = LinkedID;
        this.AccountID = AccountID;
    }
    public void setLinkedID(String LinkedID) {
        this.LinkedID = LinkedID;
    }

    public String getLinkedID() {
        return LinkedID;
    }

    public void setAccountID(String AccountID) {
        this.AccountID = AccountID;
    }

    public String getAccountID() {
        return AccountID;
    }

}
