/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.museumapplication.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Definition of ObjectType LinkedAccounts.
 *
 * @since 2020-08-03
 */
public class LinkedAccounts extends CloudDBZoneObject {
    @PrimaryKey
    @IsIndex(indexName = "index1")
    private String UID;

    private String UID2;

    private String UID3;

    private String UID4;

    public LinkedAccounts() {
        super();

    }

    public List<String> getAllUID(){
        List <String> UIDs = new ArrayList<String>();
        UIDs.add(UID);
        UIDs.add(UID2);
        UIDs.add(UID3);
        UIDs.add(UID4);
        return UIDs;
    }
    public void setUID(String UID) {
        this.UID = UID;
    }

    public String getUID() {
        return UID;
    }

    public void setUID2(String UID2) {
        this.UID2 = UID2;
    }

    public String getUID2() {
        return UID2;
    }

    public void setUID3(String UID3) {
        this.UID3 = UID3;
    }

    public String getUID3() {
        return UID3;
    }

    public void setUID4(String UID4) {
        this.UID4 = UID4;
    }

    public String getUID4() {
        return UID4;
    }

}
