/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.museumapplication.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

/**
 * Definition of ObjectType User.
 *
 * @since 2020-12-24
 */

public class User extends CloudDBZoneObject {
    @PrimaryKey
    private String uID;

    private String providerID;

    private String email;

    private String displayName;

    private String photoURL;

    public User() {
        super();

    }
    public User(String uID, String providerUID, String email, String displayName, String photoUrl){
        this.uID = uID;
        this.providerID = providerUID;
        this.email = email;
        this.displayName = displayName;
        this.photoURL = photoUrl;
    }

    public void setUID(String uID) {
        this.uID = uID;
    }

    public String getUID() {
        return uID;
    }

    public void setProviderID(String providerID) {
        this.providerID = providerID;
    }

    public String getProviderID() {
        return providerID;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getEmail() {
        return email;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setPhotoURL(String photoURL) {
        this.photoURL = photoURL;
    }

    public String getPhotoURL() {
        return photoURL;
    }

}
