/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.example.museumapplication.data;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

import java.util.Date;

/**
 * Definition of ObjectType User.
 *
 * @since 2020-08-02
 */
public class User extends CloudDBZoneObject {
    @PrimaryKey
    @IsIndex(indexName = "index1")
    private String UID;

    private String ProviderUID;

    private String Email;

    private String DisplayName;

    private String PhotoURL;

    public User() {
        super();

    }
    public User(String UID, String ProviderUID,String Email,String DisplayName, String PhotoUrl){
        this.UID = UID;
        this.ProviderUID = ProviderUID;
        this.Email = Email;
        this.DisplayName = DisplayName;
        this.PhotoURL = PhotoUrl;
    }

    public void setUID(String UID) {
        this.UID = UID;
    }

    public String getUID() {
        return UID;
    }

    public void setProviderUID(String ProviderUID) {
        this.ProviderUID = ProviderUID;
    }

    public String getProviderUID() {
        return ProviderUID;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getEmail() {
        return Email;
    }

    public void setDisplayName(String DisplayName) {
        this.DisplayName = DisplayName;
    }

    public String getDisplayName() {
        return DisplayName;
    }

    public void setPhotoURL(String PhotoURL) {
        this.PhotoURL = PhotoURL;
    }

    public String getPhotoURL() {
        return PhotoURL;
    }

}
